{{- if .Values.slo.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "oms.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "oms.name" . }}
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "oms.name" . }}
      app.kubernetes.io/component: api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
